name: Richiesta funzionalità
description: Suggerisci una nuova funzione o un miglioramento dell'app.
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrizione della funzionalità
      description: Cosa vorresti che fosse aggiunto o modificato?
      placeholder: Vorrei avere una modalità scura per usare l'app di notte...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Perché questa funzione è utile?
      description: Spiega come migliorerebbe l'esperienza d'uso o risolverebbe un problema.
      placeholder: Mi aiuterebbe a ridurre l'affaticamento visivo di sera...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Altri dettagli
      description: Vuoi aggiungere altro? Bozze, esempi, schermate...
      placeholder: Facoltativo
    validations:
      required: false
